---
- hosts: 127.0.0.1 
  connection: local 
  vars_files:
    - vars.yml

  tasks:
    - name: Build uberjar
      command: lein ring uberjar

    - name: Rsync jar to remote server
      command: rsync -avz {{project_jar_file}} {{ production_user }}@{{ production_server }}:{{ project_root }}

- hosts: production
  vars_files:
    - vars.yml
  sudo: true
  sudo_user: root

  tasks:
    - name: Kill Java program
      shell: ps -C java -o pid | tail -n 1 | xargs kill
      ignore_errors: yes

    - name: Wait until program has died
      shell: sleep 10

    - name: Setup Java program
      shell: >
        export HOSTNAME="{{ hostname }}";
        export MAPQUEST_KEY="{{ mapquest_key }}";
        export YELP_CONSUMER_KEY="{{ yelp_consumer_key}}";
        export YELP_CONSUMER_SECRET="{{ yelp_consumer_secret }}";
        export YELP_TOKEN="{{ yelp_token }}";
        export YELP_TOKEN_SECRET="{{yelp_token_secret }}";
        export PORT=80;
        nohup java -jar {{ project_root}}/{{ project_jar }} >> {{ project_root }}/ontheway.log &
